
-- Updated schema for Store Management
-- Adds foreign keys, audit table, inventory adjustments, users table, and more.
-- IMPORTANT:
-- 1) If you already have data in the original DB, adding constraints may fail. 
--    Use data-cleaning steps first (ensure referential integrity), or import into a fresh DB.
-- 2) To add constraints to an existing DB with data, you can:
--    a) SET FOREIGN_KEY_CHECKS=0; make changes; SET FOREIGN_KEY_CHECKS=1;
--    b) Or add constraints after ensuring all referenced keys exist.
-- 3) Backup your current DB before running this script.
-- File generated by ChatGPT for your project.
DROP DATABASE IF EXISTS store_management;
CREATE DATABASE store_management CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

USE store_management;

DROP TABLE IF EXISTS activity_logs;
DROP TABLE IF EXISTS promotion_redemptions;
DROP TABLE IF EXISTS payments;
DROP TABLE IF EXISTS order_items;
DROP TABLE IF EXISTS `orders`;
DROP TABLE IF EXISTS inventory_adjustments;
DROP TABLE IF EXISTS inventory;
DROP TABLE IF EXISTS products;
DROP TABLE IF EXISTS suppliers;
DROP TABLE IF EXISTS categories;
DROP TABLE IF EXISTS customers;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS promotions;

-- Parent tables first
CREATE TABLE categories (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(191) NOT NULL,
  slug VARCHAR(191) DEFAULT NULL,
  description TEXT,
  is_active TINYINT(1) NOT NULL DEFAULT 1,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY ux_categories_slug (slug)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE suppliers (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  contact_name VARCHAR(255),
  phone VARCHAR(50),
  email VARCHAR(255),
  address TEXT,
  is_active TINYINT(1) NOT NULL DEFAULT 1,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE customers (
  id INT AUTO_INCREMENT PRIMARY KEY,
  full_name VARCHAR(255) NOT NULL,
  phone VARCHAR(50),
  email VARCHAR(255),
  address TEXT,
  note TEXT,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY ux_customers_phone (phone),
  UNIQUE KEY ux_customers_email (email)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


CREATE TABLE users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(150) NOT NULL UNIQUE,
  email VARCHAR(255) UNIQUE,
  password_hash VARCHAR(512) NOT NULL,
  full_name VARCHAR(255),
  role ENUM('admin','staff') NOT NULL DEFAULT 'staff',
  is_active TINYINT(1) NOT NULL DEFAULT 1,
  locked TINYINT(1) NOT NULL DEFAULT 0,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  last_login DATETIME DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


CREATE TABLE promotions (
  id INT AUTO_INCREMENT PRIMARY KEY,
  code VARCHAR(100) NOT NULL UNIQUE,
  type ENUM('percent','fixed') NOT NULL DEFAULT 'percent',
  value DECIMAL(12,2) NOT NULL DEFAULT 0,
  min_order_amount DECIMAL(12,2) DEFAULT 0,
  start_date DATETIME DEFAULT NULL,
  end_date DATETIME DEFAULT NULL,
  usage_limit INT DEFAULT NULL,
  used_count INT DEFAULT 0,
  active TINYINT(1) NOT NULL DEFAULT 1,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


-- Products with FK to categories and suppliers
CREATE TABLE products (
  id INT AUTO_INCREMENT PRIMARY KEY,
  sku VARCHAR(100) DEFAULT NULL,
  product_name VARCHAR(255) NOT NULL,
  barcode VARCHAR(191) DEFAULT NULL,
  category_id INT DEFAULT NULL,
  supplier_id INT DEFAULT NULL,
  price DECIMAL(12,2) NOT NULL DEFAULT 0,
  cost DECIMAL(12,2) DEFAULT 0,
  unit VARCHAR(50),
  description TEXT,
  image_url VARCHAR(1024) DEFAULT NULL,
  is_active TINYINT(1) NOT NULL DEFAULT 1,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT ux_products_sku UNIQUE (sku),
  CONSTRAINT ux_products_barcode UNIQUE (barcode),
  INDEX idx_products_category (category_id),
  INDEX idx_products_supplier (supplier_id),
  CONSTRAINT fk_products_category FOREIGN KEY (category_id) REFERENCES categories(id) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT fk_products_supplier FOREIGN KEY (supplier_id) REFERENCES suppliers(id) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


-- Inventory: one record per product (normalized). Use product_id unique.
CREATE TABLE inventory (
  id INT AUTO_INCREMENT PRIMARY KEY,
  product_id INT NOT NULL,
  quantity INT NOT NULL DEFAULT 0,
  last_checked_at DATETIME DEFAULT NULL,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY ux_inventory_product (product_id),
  INDEX idx_inventory_product (product_id),
  CONSTRAINT fk_inventory_product FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Inventory adjustments log
CREATE TABLE inventory_adjustments (
  id INT AUTO_INCREMENT PRIMARY KEY,
  product_id INT NOT NULL,
  change_amount INT NOT NULL,
  reason VARCHAR(255) DEFAULT NULL,
  user_id INT DEFAULT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_inv_adj_product FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_inv_adj_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL ON UPDATE CASCADE,
  INDEX idx_inv_adj_product (product_id),
  INDEX idx_inv_adj_user (user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


-- Orders and order items
CREATE TABLE `orders` (
  id INT AUTO_INCREMENT PRIMARY KEY,
  order_number VARCHAR(100) NOT NULL UNIQUE,
  customer_id INT DEFAULT NULL,
  user_id INT DEFAULT NULL, -- staff who created the order
  status ENUM('pending','paid','cancelled','completed') NOT NULL DEFAULT 'pending',
  subtotal DECIMAL(12,2) NOT NULL DEFAULT 0,
  discount DECIMAL(12,2) NOT NULL DEFAULT 0,
  total_amount DECIMAL(12,2) NOT NULL DEFAULT 0,
  promotion_id INT DEFAULT NULL,
  note TEXT,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_orders_customer FOREIGN KEY (customer_id) REFERENCES customers(id) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT fk_orders_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT fk_orders_promo FOREIGN KEY (promotion_id) REFERENCES promotions(id) ON DELETE SET NULL ON UPDATE CASCADE,
  INDEX idx_orders_customer (customer_id),
  INDEX idx_orders_user (user_id),
  INDEX idx_orders_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


CREATE TABLE order_items (
  id INT AUTO_INCREMENT PRIMARY KEY,
  order_id INT NOT NULL,
  product_id INT NOT NULL,
  quantity INT NOT NULL DEFAULT 1,
  unit_price DECIMAL(12,2) NOT NULL DEFAULT 0,
  total_price DECIMAL(12,2) NOT NULL DEFAULT 0,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_order_items_order FOREIGN KEY (order_id) REFERENCES `orders`(id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_order_items_product FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE RESTRICT ON UPDATE CASCADE,
  INDEX idx_oi_order (order_id),
  INDEX idx_oi_product (product_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


-- Payments linked to orders
CREATE TABLE payments (
  id INT AUTO_INCREMENT PRIMARY KEY,
  order_id INT NOT NULL,
  amount DECIMAL(12,2) NOT NULL DEFAULT 0,
  method ENUM('cash','card','ecard','other') NOT NULL DEFAULT 'cash',
  transaction_ref VARCHAR(255) DEFAULT NULL,
  status ENUM('pending','completed','failed','refunded') NOT NULL DEFAULT 'completed',
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_payments_order FOREIGN KEY (order_id) REFERENCES `orders`(id) ON DELETE CASCADE ON UPDATE CASCADE,
  INDEX idx_payments_order (order_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


-- Optional: Promotion redemptions to track usage per customer/order
CREATE TABLE promotion_redemptions (
  id INT AUTO_INCREMENT PRIMARY KEY,
  promotion_id INT NOT NULL,
  customer_id INT DEFAULT NULL,
  order_id INT DEFAULT NULL,
  redeemed_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_pr_promotion FOREIGN KEY (promotion_id) REFERENCES promotions(id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_pr_customer FOREIGN KEY (customer_id) REFERENCES customers(id) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT fk_pr_order FOREIGN KEY (order_id) REFERENCES `orders`(id) ON DELETE SET NULL ON UPDATE CASCADE,
  INDEX idx_pr_promotion (promotion_id),
  INDEX idx_pr_customer (customer_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Activity / Audit logs
CREATE TABLE activity_logs (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  user_id INT DEFAULT NULL,
  action VARCHAR(191) NOT NULL, -- e.g., "create_order", "adjust_inventory"
  entity_type VARCHAR(100) DEFAULT NULL, -- e.g., "orders", "products"
  entity_id VARCHAR(100) DEFAULT NULL,
  payload JSON DEFAULT NULL,
  ip_address VARCHAR(50) DEFAULT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_activity_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL ON UPDATE CASCADE,
  INDEX idx_activity_user (user_id),
  INDEX idx_activity_action (action)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


-- Helpful indexes for reporting queries
CREATE INDEX idx_orders_created_at ON `orders` (created_at);
CREATE INDEX idx_inventory_quantity ON inventory (quantity);
CREATE INDEX idx_products_created_at ON products (created_at);

-- ===== USERS =====
INSERT INTO users (username, email, password_hash, full_name, role, is_active, locked, created_at)
VALUES
  ('admin', 'admin@example.com', '$2a$11$B5Pre4vLwlsfDIMg/gXXjuH/CyqianiPXHXSXikWE5R0djN/9Tf7.', 'Quản trị viên', 'admin', 1, 0, NOW()),
  ('staff01', 'staff01@example.com', '$2a$11$NChyYqe5MniZi.l08LVuP.SkfLMRMtyK6guvRRyq/PdaGdjYoTaO2', 'Nguyễn Văn A', 'staff', 1, 0, NOW()),
  ('staff02', 'staff02@example.com', '$2a$11$NChyYqe5MniZi.l08LVuP.SkfLMRMtyK6guvRRyq/PdaGdjYoTaO2', 'Lê Thị B', 'staff', 1, 0, NOW());

-- password của admin là admin123
-- password của staff là 123456


-- ===== CUSTOMERS (full_name, phone, email, address) =====
INSERT INTO customers (full_name, phone, email, address, created_at)
VALUES
('Khách hàng 1', '0909000001', 'kh1@mail.com', 'Địa chỉ 1', NOW()),
('Khách hàng 2', '0909000002', 'kh2@mail.com', 'Địa chỉ 2', NOW()),
('Khách hàng 3', '0909000003', 'kh3@mail.com', 'Địa chỉ 3', NOW()),
('Khách hàng 4', '0909000004', 'kh4@mail.com', 'Địa chỉ 4', NOW()),
('Khách hàng 5', '0909000005', 'kh5@mail.com', 'Địa chỉ 5', NOW()),
('Khách hàng 6', '0909000006', 'kh6@mail.com', 'Địa chỉ 6', NOW()),
('Khách hàng 7', '0909000007', 'kh7@mail.com', 'Địa chỉ 7', NOW()),
('Khách hàng 8', '0909000008', 'kh8@mail.com', 'Địa chỉ 8', NOW()),
('Khách hàng 9', '0909000009', 'kh9@mail.com', 'Địa chỉ 9', NOW()),
('Khách hàng 10', '0909000010', 'kh10@mail.com', 'Địa chỉ 10', NOW()),
('Khách hàng 11', '0909000011', 'kh11@mail.com', 'Địa chỉ 11', NOW()),
('Khách hàng 12', '0909000012', 'kh12@mail.com', 'Địa chỉ 12', NOW()),
('Khách hàng 13', '0909000013', 'kh13@mail.com', 'Địa chỉ 13', NOW()),
('Khách hàng 14', '0909000014', 'kh14@mail.com', 'Địa chỉ 14', NOW()),
('Khách hàng 15', '0909000015', 'kh15@mail.com', 'Địa chỉ 15', NOW()),
('Khách hàng 16', '0909000016', 'kh16@mail.com', 'Địa chỉ 16', NOW()),
('Khách hàng 17', '0909000017', 'kh17@mail.com', 'Địa chỉ 17', NOW()),
('Khách hàng 18', '0909000018', 'kh18@mail.com', 'Địa chỉ 18', NOW()),
('Khách hàng 19', '0909000019', 'kh19@mail.com', 'Địa chỉ 19', NOW()),
('Khách hàng 20', '0909000020', 'kh20@mail.com', 'Địa chỉ 20', NOW());

-- ===== CATEGORIES (name) =====
INSERT INTO categories (name, created_at)
VALUES
('Đồ uống', NOW()),
('Bánh kẹo', NOW()),
('Gia vị', NOW()),
('Đồ gia dụng', NOW()),
('Mỹ phẩm', NOW());

-- ===== SUPPLIERS (name, contact_name, phone, email, address) =====
INSERT INTO suppliers (name, contact_name, phone, email, address, created_at)
VALUES
('Công ty ABC', NULL, '0909123456', 'abc@gmail.com', 'Hà Nội', NOW()),
('Công ty XYZ', NULL, '0912123456', 'xyz@gmail.com', 'TP HCM', NOW()),
('Công ty 123', NULL, '0933123456', '123@gmail.com', 'Đà Nẵng', NOW());

-- ===== PRODUCTS (category_id, supplier_id, product_name, sku, price, unit) =====
-- NOTE: price inserted as decimal with 2 decimals (original values used integers; we store as .00)
INSERT INTO products (category_id, supplier_id, product_name, sku, price, unit, created_at)
VALUES
(2, 1, 'Coca Cola lon', '8900000000001', 314838.00, 'hộp', NOW()),
(1, 3, 'Pepsi lon', '8900000000002', 114807.00, 'cái', NOW()),
(3, 3, 'Trà Xanh 0 độ', '8900000000003', 415725.00, 'tuýp', NOW()),
(2, 1, 'Sting dâu', '8900000000004', 351670.00, 'cái', NOW()),
(3, 2, 'Red Bull', '8900000000005', 402179.00, 'lon', NOW()),
(2, 2, 'Bánh Oreo', '8900000000006', 209283.00, 'chai', NOW()),
(5, 3, 'Bánh Chocopie', '8900000000007', 212528.00, 'lon', NOW()),
(1, 2, 'Kẹo Alpenliebe', '8900000000008', 34313.00, 'lon', NOW()),
(5, 1, 'Kẹo bạc hà', '8900000000009', 316289.00, 'cái', NOW()),
(1, 2, 'Socola KitKat', '8900000000010', 139959.00, 'chai', NOW()),
(5, 1, 'Nước mắm Nam Ngư', '8900000000011', 51792.00, 'chai', NOW()),
(2, 2, 'Nước tương Maggi', '8900000000012', 462539.00, 'lon', NOW()),
(5, 3, 'Muối i-ốt', '8900000000013', 173302.00, 'cái', NOW()),
(1, 1, 'Bột ngọt Ajinomoto', '8900000000014', 443069.00, 'cái', NOW()),
(2, 2, 'Dầu ăn Tường An', '8900000000015', 281354.00, 'tuýp', NOW()),
(2, 1, 'Nồi cơm điện', '8900000000016', 405347.00, 'hộp', NOW()),
(1, 3, 'Ấm siêu tốc', '8900000000017', 113087.00, 'chai', NOW()),
(3, 2, 'Quạt máy', '8900000000018', 69968.00, 'hộp', NOW()),
(4, 1, 'Bếp gas mini', '8900000000019', 416845.00, 'lon', NOW()),
(3, 3, 'Máy xay sinh tố', '8900000000020', 334564.00, 'hộp', NOW()),
(1, 1, 'Sữa rửa mặt Hazeline', '8900000000021', 188475.00, 'lon', NOW()),
(4, 1, 'Kem dưỡng da Pond''s', '8900000000022', 413840.00, 'hộp', NOW()),
(3, 2, 'Dầu gội Sunsilk', '8900000000023', 158950.00, 'tuýp', NOW()),
(4, 2, 'Sữa tắm Dove', '8900000000024', 336928.00, 'chai', NOW()),
(1, 1, 'Nước hoa Romano', '8900000000025', 352508.00, 'cái', NOW()),
(1, 1, 'Cà phê G7', '8900000000026', 201228.00, 'lon', NOW()),
(2, 1, 'Trà Lipton', '8900000000027', 38039.00, 'cái', NOW()),
(2, 3, 'Sữa Vinamilk', '8900000000028', 252845.00, 'chai', NOW()),
(3, 1, 'Sữa TH True Milk', '8900000000029', 35278.00, 'hộp', NOW()),
(3, 2, 'Nước suối Lavie', '8900000000030', 331637.00, 'lon', NOW()),
(5, 3, 'Khăn giấy Tempo', '8900000000031', 102525.00, 'chai', NOW()),
(4, 3, 'Giấy vệ sinh Pulppy', '8900000000032', 495429.00, 'chai', NOW()),
(3, 2, 'Bình nước Lock&Lock', '8900000000033', 354771.00, 'gói', NOW()),
(2, 1, 'Hộp nhựa Tupperware', '8900000000034', 297415.00, 'cái', NOW()),
(1, 3, 'Dao Inox', '8900000000035', 47523.00, 'hộp', NOW()),
(3, 1, 'Bàn chải Colgate', '8900000000036', 136417.00, 'chai', NOW()),
(2, 2, 'Kem đánh răng P/S', '8900000000037', 93713.00, 'hộp', NOW()),
(2, 3, 'Nước súc miệng Listerine', '8900000000038', 223906.00, 'gói', NOW()),
(1, 2, 'Bông tẩy trang', '8900000000039', 317819.00, 'tuýp', NOW()),
(4, 1, 'Khẩu trang 3M', '8900000000040', 464252.00, 'gói', NOW()),
(3, 1, 'Bánh mì sandwich', '8900000000041', 279350.00, 'cái', NOW()),
(5, 2, 'Mì gói Hảo Hảo', '8900000000042', 9413.00, 'hộp', NOW()),
(1, 2, 'Mì Omachi', '8900000000043', 26616.00, 'hộp', NOW()),
(5, 2, 'Bún khô', '8900000000044', 350911.00, 'gói', NOW()),
(3, 1, 'Phở ăn liền', '8900000000045', 407779.00, 'tuýp', NOW()),
(1, 1, 'Nước ngọt Sprite', '8900000000046', 230083.00, 'hộp', NOW()),
(1, 3, 'Trà sữa đóng chai', '8900000000047', 15130.00, 'cái', NOW()),
(3, 3, 'Snack Oishi', '8900000000048', 43415.00, 'cái', NOW()),
(4, 2, 'Snack Lay''s', '8900000000049', 83536.00, 'tuýp', NOW()),
(1, 2, 'Kẹo dẻo Haribo', '8900000000050', 328680.00, 'cái', NOW());

-- ===== INVENTORY (product_id, quantity) =====
INSERT INTO inventory (product_id, quantity, updated_at)
VALUES
(1, 25, NOW()),(2, 169, NOW()),(3, 77, NOW()),(4, 169, NOW()),(5, 90, NOW()),
(6, 105, NOW()),(7, 125, NOW()),(8, 37, NOW()),(9, 74, NOW()),(10, 149, NOW()),
(11, 69, NOW()),(12, 23, NOW()),(13, 46, NOW()),(14, 144, NOW()),(15, 134, NOW()),
(16, 182, NOW()),(17, 99, NOW()),(18, 72, NOW()),(19, 128, NOW()),(20, 123, NOW()),
(21, 155, NOW()),(22, 78, NOW()),(23, 166, NOW()),(24, 117, NOW()),(25, 168, NOW()),
(26, 197, NOW()),(27, 36, NOW()),(28, 145, NOW()),(29, 61, NOW()),(30, 139, NOW()),
(31, 47, NOW()),(32, 154, NOW()),(33, 194, NOW()),(34, 41, NOW()),(35, 154, NOW()),
(36, 71, NOW()),(37, 49, NOW()),(38, 165, NOW()),(39, 73, NOW()),(40, 176, NOW()),
(41, 41, NOW()),(42, 34, NOW()),(43, 175, NOW()),(44, 59, NOW()),(45, 198, NOW()),
(46, 106, NOW()),(47, 99, NOW()),(48, 55, NOW()),(49, 62, NOW()),(50, 33, NOW());

-- ===== PROMOTIONS (code, type, value, start_date, end_date, min_order_amount, usage_limit, used_count, active) =====
INSERT INTO promotions (code, type, value, start_date, end_date, min_order_amount, usage_limit, used_count, active, created_at)
VALUES
('SALE10', 'percent', 10.00, '2025-01-01', '2025-12-31', 0.00, NULL, 0, 1, NOW()),
('FREESHIP50K', 'fixed', 50000.00, '2025-03-01', '2025-12-31', 300000.00, 500, 0, 1, NOW()),
('NEWUSER', 'percent', 20.00, '2025-01-01', '2025-06-30', 0.00, 1, 0, 1, NOW()),
('SUMMER15', 'percent', 15.00, '2025-06-01', '2025-08-31', 50000.00, 1000, 0, 1, NOW()),
('VIP100K', 'fixed', 100000.00, '2025-01-01', '2025-12-31', 1000000.00, 200, 0, 1, NOW());

-- ===== ORDERS (order_number, customer_id, user_id, status, subtotal, discount, total_amount, promotion_id, created_at) =====
-- NOTE: Using UUID() for order_number; subtotal computed as total_amount + discount_amount (if available)
INSERT INTO orders (order_number, customer_id, user_id, status, subtotal, discount, total_amount, promotion_id, created_at)
VALUES
(UUID(), 5, 3, 'paid', 1292330 + 100000, 100000, 1292330, 5, NOW()),
(UUID(), 17, 3, 'paid', 1731608 + 0, 0, 1731608, NULL, NOW()),
(UUID(), 8, 3, 'paid', 720782 + 0, 0, 720782, NULL, NOW()),
(UUID(), 20, 3, 'paid', 21686 + 21686, 21686, 21686, 5, NOW()),
(UUID(), 1, 2, 'paid', 94180 + 0, 0, 94180, NULL, NOW()),
(UUID(), 5, 3, 'paid', 3888671 + 100000, 100000, 3888671, 2, NOW()),
(UUID(), 9, 3, 'paid', 512594 + 102518.8, 102518.8, 512594, 4, NOW()),
(UUID(), 11, 3, 'paid', 1715029 + 171502.9, 171502.9, 1715029, 3, NOW()),
(UUID(), 11, 3, 'paid', 2484051 + 0, 0, 2484051, NULL, NOW()),
(UUID(), 11, 3, 'paid', 1070239 + 100000, 100000, 1070239, 2, NOW()),
(UUID(), 20, 3, 'paid', 1532741 + 0, 0, 1532741, NULL, NOW()),
(UUID(), 10, 2, 'paid', 1785354 + 0, 0, 1785354, NULL, NOW()),
(UUID(), 10, 3, 'paid', 1588276 + 100000, 100000, 1588276, 2, NOW()),
(UUID(), 6, 2, 'paid', 2896096 + 50000, 50000, 2896096, 2, NOW()),
(UUID(), 10, 2, 'paid', 186000 + 27900, 27900, 186000, 3, NOW()),
(UUID(), 10, 2, 'paid', 1024090 + 50000, 50000, 1024090, 5, NOW()),
(UUID(), 19, 3, 'paid', 467148 + 0, 0, 467148, NULL, NOW()),
(UUID(), 10, 2, 'paid', 394342 + 0, 0, 394342, NULL, NOW()),
(UUID(), 8, 3, 'paid', 1965637 + 294845.55, 294845.55, 1965637, 4, NOW()),
(UUID(), 3, 3, 'paid', 2889813 + 0, 0, 2889813, NULL, NOW()),
(UUID(), 9, 2, 'paid', 2288406 + 0, 0, 2288406, NULL, NOW()),
(UUID(), 17, 3, 'paid', 331008 + 0, 0, 331008, NULL, NOW()),
(UUID(), 6, 3, 'paid', 2154851 + 323227.65, 323227.65, 2154851, 1, NOW()),
(UUID(), 1, 3, 'paid', 1138686 + 170802.9, 170802.9, 1138686, 1, NOW()),
(UUID(), 2, 2, 'paid', 393847 + 100000, 100000, 393847, 5, NOW()),
(UUID(), 15, 3, 'paid', 260658 + 52131.6, 52131.6, 260658, 1, NOW()),
(UUID(), 4, 2, 'paid', 933199 + 0, 0, 933199, NULL, NOW()),
(UUID(), 16, 2, 'paid', 2609123 + 0, 0, 2609123, NULL, NOW()),
(UUID(), 4, 3, 'paid', 2406292 + 481258.4, 481258.4, 2406292, 4, NOW()),
(UUID(), 1, 3, 'paid', 2912134 + 0, 0, 2912134, NULL, NOW());

-- ===== ORDER_ITEMS (order_id, product_id, quantity, unit_price, total_price) =====
INSERT INTO order_items (order_id, product_id, quantity, unit_price, total_price, created_at)
VALUES
(1, 23, 2, 31265.00, 62530.00, NOW()),
(1, 5, 2, 205683.00, 411366.00, NOW()),
(1, 47, 1, 477948.00, 477948.00, NOW()),
(1, 25, 2, 170243.00, 340486.00, NOW()),
(2, 39, 1, 447059.00, 447059.00, NOW()),
(2, 14, 1, 51108.00, 51108.00, NOW()),
(2, 46, 3, 411147.00, 1233441.00, NOW()),
(3, 18, 3, 202167.00, 606501.00, NOW()),
(3, 34, 1, 44219.00, 44219.00, NOW()),
(3, 26, 3, 23354.00, 70062.00, NOW()),
(4, 24, 2, 10843.00, 21686.00, NOW()),
(5, 9, 1, 94180.00, 94180.00, NOW()),
(6, 18, 3, 186886.00, 560658.00, NOW()),
(6, 22, 2, 199267.00, 398534.00, NOW()),
(6, 42, 3, 215726.00, 647178.00, NOW()),
(6, 17, 3, 474268.00, 1422804.00, NOW()),
(6, 20, 3, 286499.00, 859497.00, NOW()),
(7, 8, 2, 256297.00, 512594.00, NOW()),
(8, 42, 1, 355116.00, 355116.00, NOW()),
(8, 43, 2, 129224.00, 258448.00, NOW()),
(8, 31, 3, 367155.00, 1101465.00, NOW()),
(9, 17, 2, 48755.00, 97510.00, NOW()),
(9, 12, 2, 381904.00, 763808.00, NOW()),
(9, 43, 2, 167445.00, 334890.00, NOW()),
(9, 19, 3, 429281.00, 1287843.00, NOW()),
(10, 25, 1, 232635.00, 232635.00, NOW()),
(10, 1, 2, 245362.00, 490724.00, NOW()),
(10, 23, 2, 127233.00, 254466.00, NOW()),
(10, 49, 2, 46207.00, 92414.00, NOW()),
(11, 3, 2, 347879.00, 695758.00, NOW()),
(11, 23, 3, 130215.00, 390645.00, NOW()),
(11, 4, 1, 64761.00, 64761.00, NOW()),
(11, 33, 1, 240159.00, 240159.00, NOW()),
(11, 7, 1, 141418.00, 141418.00, NOW()),
(12, 40, 2, 455428.00, 910856.00, NOW()),
(12, 46, 2, 75412.00, 150824.00, NOW()),
(12, 34, 2, 189856.00, 379712.00, NOW()),
(12, 25, 3, 114654.00, 343962.00, NOW()),
(13, 24, 2, 143251.00, 286502.00, NOW()),
(13, 23, 2, 381347.00, 762694.00, NOW()),
(13, 18, 2, 179146.00, 358292.00, NOW()),
(13, 9, 2, 90394.00, 180788.00, NOW()),
(14, 24, 2, 327016.00, 654032.00, NOW()),
(14, 2, 1, 403478.00, 403478.00, NOW()),
(14, 27, 3, 404474.00, 1213422.00, NOW()),
(14, 4, 2, 312582.00, 625164.00, NOW()),
(15, 18, 1, 105328.00, 105328.00, NOW()),
(15, 27, 2, 17303.00, 34606.00, NOW()),
(15, 50, 2, 23033.00, 46066.00, NOW()),
(16, 15, 1, 43160.00, 43160.00, NOW()),
(16, 16, 2, 18541.00, 37082.00, NOW()),
(16, 44, 1, 492698.00, 492698.00, NOW()),
(16, 41, 1, 451150.00, 451150.00, NOW()),
(17, 42, 1, 467148.00, 467148.00, NOW()),
(18, 30, 1, 64334.00, 64334.00, NOW()),
(18, 11, 1, 178454.00, 178454.00, NOW()),
(18, 20, 3, 50518.00, 151554.00, NOW()),
(19, 16, 1, 89280.00, 89280.00, NOW()),
(19, 23, 3, 404655.00, 1213965.00, NOW()),
(19, 11, 2, 331196.00, 662392.00, NOW()),
(20, 49, 1, 367325.00, 367325.00, NOW()),
(20, 32, 2, 264392.00, 528784.00, NOW()),
(20, 19, 3, 345903.00, 1037709.00, NOW()),
(20, 17, 2, 392028.00, 784056.00, NOW()),
(20, 19, 1, 171939.00, 171939.00, NOW()),
(21, 11, 3, 227666.00, 682998.00, NOW()),
(21, 25, 2, 436122.00, 872244.00, NOW()),
(21, 48, 1, 340400.00, 340400.00, NOW()),
(21, 10, 2, 58482.00, 116964.00, NOW()),
(21, 4, 2, 137900.00, 275800.00, NOW()),
(22, 40, 2, 165504.00, 331008.00, NOW()),
(23, 1, 2, 296698.00, 593396.00, NOW()),
(23, 16, 3, 384657.00, 1153971.00, NOW()),
(23, 40, 3, 135828.00, 407484.00, NOW()),
(24, 3, 3, 379562.00, 1138686.00, NOW()),
(25, 9, 1, 22063.00, 22063.00, NOW()),
(25, 16, 2, 185892.00, 371784.00, NOW()),
(26, 47, 2, 130329.00, 260658.00, NOW()),
(27, 37, 1, 448581.00, 448581.00, NOW()),
(27, 23, 1, 484618.00, 484618.00, NOW()),
(28, 20, 3, 357837.00, 1073511.00, NOW()),
(28, 34, 1, 161219.00, 161219.00, NOW()),
(28, 1, 3, 458131.00, 1374393.00, NOW()),
(29, 28, 1, 485514.00, 485514.00, NOW()),
(29, 7, 3, 487044.00, 1461132.00, NOW()),
(29, 42, 1, 235885.00, 235885.00, NOW()),
(29, 38, 1, 223761.00, 223761.00, NOW()),
(30, 25, 1, 426943.00, 426943.00, NOW()),
(30, 11, 3, 130209.00, 390627.00, NOW()),
(30, 5, 2, 73116.00, 146232.00, NOW()),
(30, 46, 2, 272220.00, 544440.00, NOW()),
(30, 23, 3, 467964.00, 1403892.00, NOW());

-- ===== PAYMENTS (order_id, amount, method, transaction_ref, status, created_at) =====
INSERT INTO payments (order_id, amount, method, transaction_ref, status, created_at)
VALUES
(1, 1192330.00, 'cash', NULL, 'completed', NOW()),
(2, 1731608.00, 'ecard', NULL, 'completed', NOW()),
(3, 720782.00, 'ecard', NULL, 'completed', NOW()),
(4, 0.00, 'card', NULL, 'pending', NOW()),
(5, 94180.00, 'cash', NULL, 'completed', NOW()),
(6, 3788671.00, 'cash', NULL, 'completed', NOW()),
(7, 410075.20, 'ecard', NULL, 'completed', NOW()),
(8, 1543526.10, 'cash', NULL, 'completed', NOW()),
(9, 2484051.00, 'cash', NULL, 'completed', NOW()),
(10, 970239.00, 'card', NULL, 'completed', NOW()),
(11, 1532741.00, 'ecard', NULL, 'completed', NOW()),
(12, 1785354.00, 'card', NULL, 'completed', NOW()),
(13, 1488276.00, 'card', NULL, 'completed', NOW()),
(14, 2846096.00, 'cash', NULL, 'completed', NOW()),
(15, 158100.00, 'card', NULL, 'completed', NOW()),
(16, 974090.00, 'cash', NULL, 'completed', NOW()),
(17, 467148.00, 'cash', NULL, 'completed', NOW()),
(18, 394342.00, 'ecard', NULL, 'completed', NOW()),
(19, 1670791.45, 'card', NULL, 'completed', NOW()),
(20, 2889813.00, 'card', NULL, 'completed', NOW()),
(21, 2288406.00, 'cash', NULL, 'completed', NOW()),
(22, 331008.00, 'ecard', NULL, 'completed', NOW()),
(23, 1831623.35, 'cash', NULL, 'completed', NOW()),
(24, 967883.10, 'ecard', NULL, 'completed', NOW()),
(25, 293847.00, 'cash', NULL, 'completed', NOW()),
(26, 208526.40, 'cash', NULL, 'completed', NOW()),
(27, 933199.00, 'cash', NULL, 'completed', NOW()),
(28, 2609123.00, 'card', NULL, 'completed', NOW()),
(29, 1925033.60, 'cash', NULL, 'completed', NOW()),
(30, 2912134.00, 'card', NULL, 'completed', NOW());

ALTER TABLE promotions 
ADD COLUMN max_discount DECIMAL(12, 2) NULL;

ALTER TABLE promotions 
ADD COLUMN description VARCHAR(1000) NULL;
 
ALTER TABLE promotions
ADD COLUMN is_deleted TINYINT(1) NOT NULL DEFAULT 0 AFTER updated_at,
ADD COLUMN deleted_at DATETIME NULL AFTER is_deleted;

ALTER TABLE customers
ADD COLUMN is_active boolean NOT NULL DEFAULT TRUE