-- Updated schema for Store Management
-- Adds foreign keys, audit table, inventory adjustments, users table, and more.
-- IMPORTANT:
-- 1) If you already have data in the original DB, adding constraints may fail. 
--    Use data-cleaning steps first (ensure referential integrity), or import into a fresh DB.
-- 2) To add constraints to an existing DB with data, you can:
--    a) SET FOREIGN_KEY_CHECKS=0; make changes; SET FOREIGN_KEY_CHECKS=1;
--    b) Or add constraints after ensuring all referenced keys exist.
-- 3) Backup your current DB before running this script.
-- File generated by ChatGPT for your project.
DROP DATABASE IF EXISTS storeApp;
CREATE DATABASE storeApp CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

USE storeApp;

DROP TABLE IF EXISTS activity_logs;
DROP TABLE IF EXISTS promotion_redemptions;
DROP TABLE IF EXISTS payments;
DROP TABLE IF EXISTS order_items;
DROP TABLE IF EXISTS `orders`;
DROP TABLE IF EXISTS inventory_adjustments;
DROP TABLE IF EXISTS inventory;
DROP TABLE IF EXISTS products;
DROP TABLE IF EXISTS suppliers;
DROP TABLE IF EXISTS categories;
DROP TABLE IF EXISTS customers;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS user_carts;
DROP TABLE IF EXISTS promotions;
DROP TABLE IF EXISTS units;

-- Parent tables first
CREATE TABLE categories (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(191) NOT NULL,
  slug VARCHAR(191) DEFAULT NULL,
  description TEXT,
  is_active TINYINT(1) NOT NULL DEFAULT 1,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY ux_categories_slug (slug)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE suppliers (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  contact_name VARCHAR(255),
  phone VARCHAR(50),
  email VARCHAR(255),
  address TEXT,
  is_active TINYINT(1) NOT NULL DEFAULT 1,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(150) NOT NULL UNIQUE,
  email VARCHAR(255) UNIQUE,
  password_hash VARCHAR(512) NOT NULL,
  full_name VARCHAR(255),
  role ENUM('admin','staff') NOT NULL DEFAULT 'staff',
  is_active TINYINT(1) NOT NULL DEFAULT 1,
  locked TINYINT(1) NOT NULL DEFAULT 0,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  last_login DATETIME DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE user_carts (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT NOT NULL,
  cart_json LONGTEXT NOT NULL,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_usercarts_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE,
  UNIQUE KEY ux_usercart_user (user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE customers (
  id INT AUTO_INCREMENT PRIMARY KEY,
  email VARCHAR(255) NOT NULL,
  password_hash VARCHAR(512) NULL,
  full_name VARCHAR(255) NOT NULL,
  phone VARCHAR(50),
  address TEXT,
  note TEXT,
  is_active TINYINT(1) NOT NULL DEFAULT 1,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY ux_customers_phone (phone),
  UNIQUE KEY ux_customers_email (email)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE promotions (
  id INT AUTO_INCREMENT PRIMARY KEY,
  code VARCHAR(100) NOT NULL UNIQUE,
  type ENUM('percent','fixed') NOT NULL DEFAULT 'percent',
  value DECIMAL(12,2) NOT NULL DEFAULT 0,
  min_order_amount DECIMAL(12,2) DEFAULT 0,
  start_date DATETIME DEFAULT NULL,
  end_date DATETIME DEFAULT NULL,
  usage_limit INT DEFAULT NULL,
  used_count INT DEFAULT 0,
  active TINYINT(1) NOT NULL DEFAULT 1,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE units (
  id INT AUTO_INCREMENT PRIMARY KEY,
  code VARCHAR(50) NOT NULL UNIQUE,
  name VARCHAR(255) NOT NULL,
  is_active TINYINT(1) NOT NULL DEFAULT 1,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_units_code (code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Products with FK to categories and suppliers
CREATE TABLE products (
  id INT AUTO_INCREMENT PRIMARY KEY,
  sku VARCHAR(100) DEFAULT NULL,
  product_name VARCHAR(255) NOT NULL,
  barcode VARCHAR(191) DEFAULT NULL,
  category_id INT DEFAULT NULL,
  supplier_id INT DEFAULT NULL,
  price DECIMAL(12,2) NOT NULL DEFAULT 0,
  cost DECIMAL(12,2) DEFAULT 0,
  unit_id INT DEFAULT NULL,
  description TEXT,
  image_url VARCHAR(1024) DEFAULT NULL,
  is_active TINYINT(1) NOT NULL DEFAULT 1,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT ux_products_sku UNIQUE (sku),
  CONSTRAINT ux_products_barcode UNIQUE (barcode),
  INDEX idx_products_category (category_id),
  INDEX idx_products_supplier (supplier_id),
  INDEX idx_products_unit (unit_id),
  CONSTRAINT fk_products_category FOREIGN KEY (category_id) REFERENCES categories(id) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT fk_products_supplier FOREIGN KEY (supplier_id) REFERENCES suppliers(id) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT fk_products_unit FOREIGN KEY (unit_id) REFERENCES units(id) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


-- Inventory: one record per product (normalized). Use product_id unique.
CREATE TABLE inventory (
  id INT AUTO_INCREMENT PRIMARY KEY,
  product_id INT NOT NULL,
  quantity INT NOT NULL DEFAULT 0,
  last_checked_at DATETIME DEFAULT NULL,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY ux_inventory_product (product_id),
  INDEX idx_inventory_product (product_id),
  CONSTRAINT fk_inventory_product FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Inventory adjustments log
CREATE TABLE inventory_adjustments (
  id INT AUTO_INCREMENT PRIMARY KEY,
  product_id INT NOT NULL,
  change_amount INT NOT NULL,
  reason VARCHAR(255) DEFAULT NULL,
  user_id INT DEFAULT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_inv_adj_product FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_inv_adj_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL ON UPDATE CASCADE,
  INDEX idx_inv_adj_product (product_id),
  INDEX idx_inv_adj_user (user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


-- Orders and order items
CREATE TABLE `orders` (
  id INT AUTO_INCREMENT PRIMARY KEY,
  order_number VARCHAR(100) NOT NULL UNIQUE,
  customer_id INT DEFAULT NULL,
  staff_id INT DEFAULT NULL, -- nhân viên xử lý đơn (NULL = đơn online)
  status ENUM('pending','paid','cancelled','completed') NOT NULL DEFAULT 'pending',
  subtotal DECIMAL(12,2) NOT NULL DEFAULT 0,
  discount DECIMAL(12,2) NOT NULL DEFAULT 0,
  total_amount DECIMAL(12,2) NOT NULL DEFAULT 0,
  promotion_id INT DEFAULT NULL,
  note TEXT,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_orders_customer FOREIGN KEY (customer_id) REFERENCES customers(id) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT fk_orders_staff FOREIGN KEY (staff_id) REFERENCES users(id) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT fk_orders_promo FOREIGN KEY (promotion_id) REFERENCES promotions(id) ON DELETE SET NULL ON UPDATE CASCADE,
  INDEX idx_orders_customer (customer_id),
  INDEX idx_orders_staff (staff_id),
  INDEX idx_orders_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


CREATE TABLE order_items (
  id INT AUTO_INCREMENT PRIMARY KEY,
  order_id INT NOT NULL,
  product_id INT NOT NULL,
  quantity INT NOT NULL DEFAULT 1,
  unit_price DECIMAL(12,2) NOT NULL DEFAULT 0,
  total_price DECIMAL(12,2) NOT NULL DEFAULT 0,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_order_items_order FOREIGN KEY (order_id) REFERENCES `orders`(id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_order_items_product FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE RESTRICT ON UPDATE CASCADE,
  INDEX idx_oi_order (order_id),
  INDEX idx_oi_product (product_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


-- Payments linked to orders
CREATE TABLE payments (
  id INT AUTO_INCREMENT PRIMARY KEY,
  order_id INT NOT NULL,
  amount DECIMAL(12,2) NOT NULL DEFAULT 0,
  method ENUM('cash','card','ecard','other') NOT NULL DEFAULT 'cash',
  transaction_ref VARCHAR(255) DEFAULT NULL,
  status ENUM('pending','completed','failed','refunded') NOT NULL DEFAULT 'completed',
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_payments_order FOREIGN KEY (order_id) REFERENCES `orders`(id) ON DELETE CASCADE ON UPDATE CASCADE,
  INDEX idx_payments_order (order_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


-- Optional: Promotion redemptions to track usage per customer/order
CREATE TABLE promotion_redemptions (
  id INT AUTO_INCREMENT PRIMARY KEY,
  promotion_id INT NOT NULL,
  customer_id INT DEFAULT NULL,
  order_id INT DEFAULT NULL,
  redeemed_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_pr_promotion FOREIGN KEY (promotion_id) REFERENCES promotions(id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_pr_customer FOREIGN KEY (customer_id) REFERENCES customers(id) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT fk_pr_order FOREIGN KEY (order_id) REFERENCES `orders`(id) ON DELETE SET NULL ON UPDATE CASCADE,
  INDEX idx_pr_promotion (promotion_id),
  INDEX idx_pr_customer (customer_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Activity / Audit logs
CREATE TABLE activity_logs (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  user_id INT DEFAULT NULL,
  action VARCHAR(191) NOT NULL, -- e.g., "create_order", "adjust_inventory"
  entity_type VARCHAR(100) DEFAULT NULL, -- e.g., "orders", "products"
  entity_id VARCHAR(100) DEFAULT NULL,
  payload JSON DEFAULT NULL,
  ip_address VARCHAR(50) DEFAULT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_activity_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL ON UPDATE CASCADE,
  INDEX idx_activity_user (user_id),
  INDEX idx_activity_action (action)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


-- Helpful indexes for reporting queries
CREATE INDEX idx_orders_created_at ON `orders` (created_at);
CREATE INDEX idx_inventory_quantity ON inventory (quantity);
CREATE INDEX idx_products_created_at ON products (created_at);

-- ===== USERS =====
INSERT INTO users (username, email, password_hash, full_name, role, is_active, locked, created_at)
VALUES
  ('admin', 'admin@example.com', '$2a$11$B5Pre4vLwlsfDIMg/gXXjuH/CyqianiPXHXSXikWE5R0djN/9Tf7.', 'Quản trị viên', 'admin', 1, 0, NOW()),
  ('staff01', 'staff01@example.com', '$2a$11$NChyYqe5MniZi.l08LVuP.SkfLMRMtyK6guvRRyq/PdaGdjYoTaO2', 'Nguyễn Văn A', 'staff', 1, 0, NOW()),
  ('staff02', 'staff02@example.com', '$2a$11$NChyYqe5MniZi.l08LVuP.SkfLMRMtyK6guvRRyq/PdaGdjYoTaO2', 'Lê Thị B', 'staff', 1, 0, NOW());

-- password của admin là admin123
-- password của staff là 123456


-- ===== CUSTOMERS (email, password_hash, full_name, phone, address) =====
-- password của customer là 123456
INSERT INTO customers (email, password_hash, full_name, phone, address, is_active, created_at)
VALUES
('customer01@example.com', '$2a$11$NChyYqe5MniZi.l08LVuP.SkfLMRMtyK6guvRRyq/PdaGdjYoTaO2', 'Khách hàng 1', '0909000001', 'Địa chỉ 1', 1, NOW()),
('customer02@example.com', '$2a$11$NChyYqe5MniZi.l08LVuP.SkfLMRMtyK6guvRRyq/PdaGdjYoTaO2', 'Khách hàng 2', '0909000002', 'Địa chỉ 2', 1, NOW()),
('kh3@mail.com', NULL, 'Khách hàng 3', '0909000003', 'Địa chỉ 3', 1, NOW()),
('kh4@mail.com', NULL, 'Khách hàng 4', '0909000004', 'Địa chỉ 4', 1, NOW()),
('kh5@mail.com', NULL, 'Khách hàng 5', '0909000005', 'Địa chỉ 5', 1, NOW()),
('kh6@mail.com', NULL, 'Khách hàng 6', '0909000006', 'Địa chỉ 6', 1, NOW()),
('kh7@mail.com', NULL, 'Khách hàng 7', '0909000007', 'Địa chỉ 7', 1, NOW()),
('kh8@mail.com', NULL, 'Khách hàng 8', '0909000008', 'Địa chỉ 8', 1, NOW()),
('kh9@mail.com', NULL, 'Khách hàng 9', '0909000009', 'Địa chỉ 9', 1, NOW()),
('kh10@mail.com', NULL, 'Khách hàng 10', '0909000010', 'Địa chỉ 10', 1, NOW()),
('kh11@mail.com', NULL, 'Khách hàng 11', '0909000011', 'Địa chỉ 11', 1, NOW()),
('kh12@mail.com', NULL, 'Khách hàng 12', '0909000012', 'Địa chỉ 12', 1, NOW()),
('kh13@mail.com', NULL, 'Khách hàng 13', '0909000013', 'Địa chỉ 13', 1, NOW()),
('kh14@mail.com', NULL, 'Khách hàng 14', '0909000014', 'Địa chỉ 14', 1, NOW()),
('kh15@mail.com', NULL, 'Khách hàng 15', '0909000015', 'Địa chỉ 15', 1, NOW()),
('kh16@mail.com', NULL, 'Khách hàng 16', '0909000016', 'Địa chỉ 16', 1, NOW()),
('kh17@mail.com', NULL, 'Khách hàng 17', '0909000017', 'Địa chỉ 17', 1, NOW()),
('kh18@mail.com', NULL, 'Khách hàng 18', '0909000018', 'Địa chỉ 18', 1, NOW()),
('kh19@mail.com', NULL, 'Khách hàng 19', '0909000019', 'Địa chỉ 19', 1, NOW()),
('kh20@mail.com', NULL, 'Khách hàng 20', '0909000020', 'Địa chỉ 20', 1, NOW());

-- ===== CATEGORIES (name) =====
INSERT INTO categories (name, created_at)
VALUES
('Đồ uống', NOW()),
('Bánh kẹo', NOW()),
('Gia vị', NOW()),
('Đồ gia dụng', NOW()),
('Mỹ phẩm', NOW()),
('Thực phẩm tươi sống', NOW()),         
('Điện tử & Phụ kiện', NOW()),       
('Dược phẩm & Y tế', NOW()),     
('Văn phòng phẩm', NOW()),      
('Thủy hải sản', NOW());

-- ===== SUPPLIERS (name, contact_name, phone, email, address) =====
INSERT INTO suppliers (name, contact_name, phone, email, address, created_at)
VALUES
('Công ty TNHH Đồ uống Quốc tế ABC', 'Nguyễn Văn A', '0909123456', 'abc@gmail.com', 'Số 123, Đường Láng, Quận Đống Đa, Hà Nội', NOW()),
('Công ty CP Thương mại & Phân phối XYZ', 'Trần Thị B', '0912123456', 'xyz@gmail.com', 'Số 456, Nguyễn Văn Linh, Quận 7, TP HCM', NOW()),
('Công ty TNHH Sản xuất 123', 'Lê Văn C', '0933123456', '123@gmail.com', 'Số 789, Đường 2/9, Quận Hải Châu, Đà Nẵng', NOW()),
('Công ty Thực phẩm Việt', 'Phạm Minh D', '0909123457', 'thucphamviet@company.com', 'Khu công nghiệp Bắc Thăng Long, Hà Nội', NOW()),
('Công ty Đồ uống Sài Gòn', 'Hoàng Thị E', '0912123457', 'douongsaigon@company.com', 'Số 321, Lê Văn Việt, Quận 9, TP HCM', NOW()),
('Công ty Gia dụng Toàn Cầu', 'Đặng Văn F', '0933123457', 'giadungtoancau@company.com', 'Khu công nghiệp Hòa Khánh, Đà Nẵng', NOW()),
('Công ty Mỹ phẩm Hàn Quốc', 'Kim Soo G', '0909123458', 'myphamkorea@company.com', 'Tầng 5, Tòa nhà Vina, Quận 1, TP HCM', NOW()),
('Công ty Bánh kẹo Hữu Nghị', 'Ngô Thị H', '0912123458', 'banhkeohuunghi@company.com', 'Số 55, Minh Khai, Quận Hai Bà Trưng, Hà Nội', NOW()),
('Công ty Gia vị Phương Nam', 'Võ Văn I', '0933123458', 'giaviphuongnam@company.com', 'Khu chế xuất Tân Thuận, Quận 7, TP HCM', NOW()),
('Công ty Điện tử Viễn Thông', 'Trương Văn J', '0909123459', 'dientuvienthong@company.com', 'Khu công nghiệp Sóng Thần, Bình Dương', NOW()),
('Công ty Văn phòng phẩm STC', 'Lý Thị K', '0912123459', 'vanphongphamstc@company.com', 'Số 88, Lê Hồng Phong, Quận 10, TP HCM', NOW()),
('Công ty Dược phẩm Việt Đức', 'Mai Văn L', '0933123459', 'duocphamvietduc@company.com', 'Khu công nghiệp Yên Phong, Bắc Ninh', NOW()),
('Công ty Thủy hải sản Biển Đông', 'Bùi Thị M', '0909123460', 'haisanbiendong@company.com', 'Cảng cá Thọ Quang, Đà Nẵng', NOW());

-- ===== THÊM DỮ LIỆU MẪU CHO BẢNG UNITS =====
INSERT INTO units (code, name, created_at) VALUES
('pcs', 'Cái', NOW()),
('box', 'Hộp', NOW()),
('bottle', 'Chai', NOW()),
('can', 'Lon', NOW()),
('tube', 'Tuýp', NOW()),
('pack', 'Gói', NOW()),
('kg', 'Kilogram', NOW()),
('liter', 'Lít', NOW()),
('pair', 'Đôi', NOW()),
('set', 'Bộ', NOW()),
('roll', 'Cuộn', NOW()),             
('sheet', 'Tờ', NOW()),             
('bag', 'Túi', NOW());             

-- ===== PRODUCTS (category_id, supplier_id, product_name, sku, price, unit) =====
INSERT INTO products (category_id, supplier_id, product_name, sku, price, unit_id, created_at)
VALUES
(1, 1, 'Coca Cola lon', '8900000000001', 15000.00, 4, NOW()),
(1, 5, 'Pepsi lon', '8900000000002', 15000.00, 4, NOW()),
(1, 1, 'Trà Xanh 0 độ', '8900000000003', 12000.00, 3, NOW()),
(1, 5, 'Sting dâu', '8900000000004', 12000.00, 3, NOW()),
(1, 1, 'Red Bull', '8900000000005', 20000.00, 4, NOW()),
(1, 1, 'Nước ngọt Sprite', '8900000000046', 15000.00, 3, NOW()),
(1, 5, 'Trà sữa đóng chai', '8900000000047', 20000.00, 3, NOW()),
(1, 5, 'Nước cam ép', '8900000000054', 25000.00, 3, NOW()),
(1, 5, 'Sinh tố đóng chai', '8900000000055', 30000.00, 3, NOW()),
(1, 5, 'Bia Tiger lon', '8900000000056', 20000.00, 4, NOW()),
(1, 1, 'Trà Lipton', '8900000000027', 10000.00, 3, NOW()),
(1, 4, 'Sữa Vinamilk', '8900000000028', 12000.00, 3, NOW()),
(1, 4, 'Sữa TH True Milk', '8900000000029', 15000.00, 3, NOW()),
(1, 5, 'Nước suối Lavie', '8900000000030', 8000.00, 4, NOW()),
(1, 9, 'Cà phê G7', '8900000000026', 50000.00, 3, NOW()),
(2, 8, 'Bánh Oreo', '8900000000006', 25000.00, 6, NOW()),
(2, 8, 'Bánh Chocopie', '8900000000007', 20000.00, 6, NOW()),
(2, 8, 'Kẹo Alpenliebe', '8900000000008', 5000.00, 6, NOW()),
(2, 8, 'Kẹo bạc hà', '8900000000009', 10000.00, 6, NOW()),
(2, 8, 'Socola KitKat', '8900000000010', 15000.00, 6, NOW()),
(2, 4, 'Snack Oishi', '8900000000048', 10000.00, 6, NOW()),
(2, 8, 'Snack Lay''s', '8900000000049', 15000.00, 6, NOW()),
(2, 8, 'Kẹo dẻo Haribo', '8900000000050', 20000.00, 6, NOW()),
(2, 8, 'Bánh quy bơ', '8900000000063', 30000.00, 6, NOW()),
(2, 8, 'Kẹo cao su', '8900000000064', 5000.00, 6, NOW()),
(2, 8, 'Bánh gato mini', '8900000000065', 50000.00, 2, NOW()),
(3, 9, 'Nước mắm Nam Ngư', '8900000000011', 35000.00, 3, NOW()),
(3, 9, 'Nước tương Maggi', '8900000000012', 25000.00, 3, NOW()),
(3, 9, 'Muối i-ốt', '8900000000013', 5000.00, 6, NOW()),
(3, 9, 'Bột ngọt Ajinomoto', '8900000000014', 15000.00, 6, NOW()),
(3, 9, 'Dầu ăn Tường An', '8900000000015', 45000.00, 3, NOW()),
(3, 9, 'Hạt nêm Knorr', '8900000000066', 20000.00, 6, NOW()),
(3, 9, 'Tương ớt Chin-su', '8900000000067', 15000.00, 3, NOW()),
(3, 9, 'Giấm gạo lên men', '8900000000068', 12000.00, 3, NOW()),
(4, 6, 'Nồi cơm điện', '8900000000016', 500000.00, 1, NOW()),
(4, 6, 'Ấm siêu tốc', '8900000000017', 300000.00, 1, NOW()),
(4, 6, 'Quạt máy', '8900000000018', 400000.00, 1, NOW()),
(4, 6, 'Bếp gas mini', '8900000000019', 600000.00, 1, NOW()),
(4, 6, 'Máy xay sinh tố', '8900000000020', 350000.00, 1, NOW()),
(4, 6, 'Bình nước Lock&Lock', '8900000000033', 150000.00, 1, NOW()),
(4, 6, 'Hộp nhựa Tupperware', '8900000000034', 80000.00, 1, NOW()),
(4, 6, 'Dao Inox', '8900000000035', 50000.00, 1, NOW()),
(4, 6, 'Nồi áp suất điện', '8900000000057', 800000.00, 1, NOW()),
(4, 6, 'Lò vi sóng', '8900000000058', 1200000.00, 1, NOW()),
(4, 6, 'Máy lọc không khí', '8900000000059', 1500000.00, 1, NOW()),
(5, 7, 'Sữa rửa mặt Hazeline', '8900000000021', 75000.00, 5, NOW()),
(5, 7, 'Kem dưỡng da Pond''s', '8900000000022', 120000.00, 5, NOW()),
(5, 7, 'Dầu gội Sunsilk', '8900000000023', 80000.00, 3, NOW()),
(5, 7, 'Sữa tắm Dove', '8900000000024', 90000.00, 3, NOW()),
(5, 7, 'Nước hoa Romano', '8900000000025', 250000.00, 3, NOW()),
(5, 7, 'Serum chống lão hóa', '8900000000060', 350000.00, 3, NOW()),
(5, 7, 'Mặt nạ dưỡng da', '8900000000061', 20000.00, 1, NOW()),
(5, 7, 'Kem chống nắng SPF50', '8900000000062', 150000.00, 5, NOW()),
(6, 4, 'Bánh mì sandwich', '8900000000041', 20000.00, 1, NOW()),
(6, 4, 'Thịt bò tươi', '8900000000051', 250000.00, 7, NOW()),
(6, 4, 'Cá hồi phi lê', '8900000000052', 350000.00, 7, NOW()),
(6, 4, 'Rau củ đông lạnh', '8900000000053', 50000.00, 6, NOW()),
(6, 4, 'Mì gói Hảo Hảo', '8900000000042', 5000.00, 6, NOW()),
(6, 4, 'Mì Omachi', '8900000000043', 7000.00, 6, NOW()),
(6, 4, 'Bún khô', '8900000000044', 15000.00, 6, NOW()),
(6, 4, 'Phở ăn liền', '8900000000045', 10000.00, 6, NOW()),
(7, 10, 'Tai nghe Bluetooth', '8900000000069', 300000.00, 1, NOW()),
(7, 10, 'Sạc dự phòng', '8900000000070', 200000.00, 1, NOW()),
(7, 10, 'Cáp sạc nhanh', '8900000000071', 50000.00, 1, NOW()),
(8, 12, 'Bàn chải Colgate', '8900000000036', 25000.00, 1, NOW()),
(8, 12, 'Kem đánh răng P/S', '8900000000037', 35000.00, 5, NOW()),
(8, 12, 'Nước súc miệng Listerine', '8900000000038', 45000.00, 3, NOW()),
(8, 12, 'Bông tẩy trang', '8900000000039', 20000.00, 6, NOW()),
(8, 12, 'Khẩu trang 3M', '8900000000040', 50000.00, 6, NOW()),
(8, 12, 'Vitamin C 500mg', '8900000000075', 80000.00, 6, NOW()),
(8, 12, 'Paracetamol 500mg', '8900000000076', 15000.00, 6, NOW()),
(8, 12, 'Băng gạc y tế', '8900000000077', 25000.00, 6, NOW()),
(9, 11, 'Khăn giấy Tempo', '8900000000031', 20000.00, 6, NOW()),
(9, 11, 'Giấy vệ sinh Pulppy', '8900000000032', 35000.00, 10, NOW()),
(9, 11, 'Bút bi xanh', '8900000000072', 5000.00, 1, NOW()),
(9, 11, 'Vở học sinh 96 trang', '8900000000073', 15000.00, 1, NOW()),
(9, 11, 'Bút highlight', '8900000000074', 12000.00, 1, NOW()),
(10, 13, 'Tôm sú tươi', '8900000000078', 280000.00, 7, NOW()),
(10, 13, 'Mực ống', '8900000000079', 220000.00, 7, NOW()),
(10, 13, 'Cá ngừ đại dương', '8900000000080', 320000.00, 7, NOW());

-- ===== INVENTORY (product_id, quantity) =====
INSERT INTO inventory (product_id, quantity, updated_at)
VALUES
(1, 25, NOW()),(2, 169, NOW()),(3, 77, NOW()),(4, 169, NOW()),(5, 90, NOW()),
(6, 105, NOW()),(7, 125, NOW()),(8, 37, NOW()),(9, 74, NOW()),(10, 149, NOW()),
(11, 69, NOW()),(12, 23, NOW()),(13, 46, NOW()),(14, 144, NOW()),(15, 134, NOW()),
(16, 182, NOW()),(17, 99, NOW()),(18, 72, NOW()),(19, 128, NOW()),(20, 123, NOW()),
(21, 155, NOW()),(22, 78, NOW()),(23, 166, NOW()),(24, 117, NOW()),(25, 168, NOW()),
(26, 197, NOW()),(27, 36, NOW()),(28, 145, NOW()),(29, 61, NOW()),(30, 139, NOW()),
(31, 47, NOW()),(32, 154, NOW()),(33, 194, NOW()),(34, 41, NOW()),(35, 154, NOW()),
(36, 71, NOW()),(37, 49, NOW()),(38, 165, NOW()),(39, 73, NOW()),(40, 176, NOW()),
(41, 41, NOW()),(42, 34, NOW()),(43, 175, NOW()),(44, 59, NOW()),(45, 198, NOW()),
(46, 106, NOW()),(47, 99, NOW()),(48, 55, NOW()),(49, 62, NOW()),(50, 33, NOW()),
(51, 45, NOW()),(52, 67, NOW()),(53, 88, NOW()),(54, 92, NOW()),(55, 76, NOW()),
(56, 54, NOW()),(57, 63, NOW()),(58, 71, NOW()),(59, 82, NOW()),(60, 93, NOW()),
(61, 105, NOW()),(62, 114, NOW()),(63, 126, NOW()),(64, 138, NOW()),(65, 147, NOW()),
(66, 155, NOW()),(67, 163, NOW()),(68, 172, NOW()),(69, 181, NOW()),(70, 192, NOW()),
(71, 203, NOW()),(72, 215, NOW()),(73, 224, NOW()),(74, 233, NOW()),(75, 242, NOW()),
(76, 251, NOW()),(77, 263, NOW()),(78, 274, NOW()),(79, 285, NOW()),(80, 296, NOW());

-- ===== PROMOTIONS (code, type, value, start_date, end_date, min_order_amount, usage_limit, used_count, active) =====
INSERT INTO promotions (code, type, value, start_date, end_date, min_order_amount, usage_limit, used_count, active, created_at)
VALUES
('SALE10', 'percent', 10.00, '2025-01-01', '2025-12-31', 0.00, NULL, 0, 1, NOW()),
('FREESHIP50K', 'fixed', 50000.00, '2025-03-01', '2025-12-31', 300000.00, 500, 0, 1, NOW()),
('NEWUSER', 'percent', 20.00, '2025-01-01', '2025-06-30', 0.00, 1, 0, 1, NOW()),
('SUMMER15', 'percent', 15.00, '2025-06-01', '2025-08-31', 50000.00, 1000, 0, 1, NOW()),
('VIP100K', 'fixed', 100000.00, '2025-01-01', '2025-12-31', 1000000.00, 200, 0, 1, NOW());

ALTER TABLE promotions 
ADD COLUMN max_discount DECIMAL(12, 2) NULL;

ALTER TABLE promotions 
ADD COLUMN description VARCHAR(1000) NULL;
 
ALTER TABLE promotions
ADD COLUMN is_deleted TINYINT(1) NOT NULL DEFAULT 0 AFTER updated_at,
ADD COLUMN deleted_at DATETIME NULL AFTER is_deleted;

-- Cập nhật giá trị max_discount cho các promotion
UPDATE promotions SET max_discount = 50000.00 WHERE code = 'SALE10';
UPDATE promotions SET max_discount = 50000.00 WHERE code = 'FREESHIP50K';
UPDATE promotions SET max_discount = 100000.00 WHERE code = 'NEWUSER';
UPDATE promotions SET max_discount = 100000.00 WHERE code = 'SUMMER15';
UPDATE promotions SET max_discount = 100000.00 WHERE code = 'VIP100K';

-- Thêm description cho promotions
UPDATE promotions SET description = 'Giảm 10% cho tất cả đơn hàng' WHERE code = 'SALE10';
UPDATE promotions SET description = 'Miễn phí vận chuyển 50k cho đơn từ 300k' WHERE code = 'FREESHIP50K';
UPDATE promotions SET description = 'Giảm 20% cho khách hàng mới' WHERE code = 'NEWUSER';
UPDATE promotions SET description = 'Giảm 15% mùa hè' WHERE code = 'SUMMER15';
UPDATE promotions SET description = 'Giảm 100k cho khách VIP' WHERE code = 'VIP100K';
-- ===== AI CONVERSATIONS & MESSAGES =====
CREATE TABLE ai_conversations (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT NOT NULL,
  title VARCHAR(255),
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_ai_conversations_user (user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE ai_messages (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  conversation_id INT NOT NULL,
  role VARCHAR(20) NOT NULL,
  content LONGTEXT NOT NULL,
  function_called VARCHAR(100),
  function_data JSON,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_ai_messages_conversation (conversation_id),
  CONSTRAINT fk_ai_messages_conversation FOREIGN KEY (conversation_id) REFERENCES ai_conversations(id) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
